server:
  port: '8089'

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it
    port: 443
    #headers:
    # User-Agent: OpenMove-Bikesharing-Client
  stations:
    path: /v2/flat%2Cnode/BikesharingStation?distinct=true
    #example of custom host and port for specific endpoint
    #hostname: ${STATIONS_HOST}
    #port: ${STATIONS_PORT}

  bays:
    path: /v2/flat%2Cnode/Bicyclestationbay?distinct=true

  bikes:
    path: /v2/flat%2Cnode/Bicycle?distinct=true
